apiVersion: v1
data:
  FRONTEND_URL: aHR0cHM6Ly9sZWFybmluZy1mcm9udC5vZmZpY2VicmFpbi5jb20=
  NODE_ENV: ZGV2ZWxvcG1lbnQ=
  VITE_API_URL: aHR0cHM6Ly9sZWFybmluZy1iYWNrLm9mZmljZWJyYWluLmNvbS9hcGk=
  VITE_LOGROCKET_APP_ID: aThpbHFtL3Byb3NwZWN0bHktYmV0YS12aXN0YWdl
  VITE_LOGROCKET_ENABLED: dHJ1ZQ==
  VITE_SEARCH_ENGINE: dHlwZXNlbnNl
  VITE_STRIPE_PUBLIC_KEY: cGtfdGVzdF81MVNJM1g3SVVNaGgxZmJiUTU5R05vZ2k2VTYyMHd3REJwU2R6aXJBUVVPSkRDZ1hVYWZLME84ZVhLYmpPTVFJNWpZaTRjanRmRlpnOThvNXlIZmVja01ZZzAwNVJ0dlZEWUo=
  VITE_TAWK_PROPERTY_ID: NjlhZWFhZTdkODJlNzIxYzM0ZTI0MWQz
  VITE_TAWK_WIDGET_ID: MWpqOTZjZzFi
kind: Secret
metadata:
  name: prospectly-frontend-secret
