apiVersion: v1
kind: Secret
metadata:
  name: prospectly-frontend-secret
  namespace: default
type: Opaque
stringData:
  SSR_API_URL: "https://learning-back.officebrain.com/api"
  # Note: In a real GitOps setup (like ArgoCD or Flux), you should encrypt this file 
  # using SealedSecrets, SOPS, or load it from an external Secret Manager (AWS Secrets Manager/Vault).
