export const ApiTagsEnum = {
  Profiles: "Profiles",
  ResendWebhooks: "Resend Webhooks",
  BountyStages: "Bounty Stages",
  Disputes: "Disputes",
  ContactSourceStatus: "Contact Source Status",
  Finances: "Finances",
  Calendar: "Calendar",
  Stripe: "Stripe",
  Contacts: "Contacts",
  IntroductionPotentialConnectors: "Introduction Potential Connectors",
  Introductions: "Introductions",
  IntroductionRequests: "Introduction Requests",
  Auth: "Auth",
  Subscriptions: "Subscriptions",
  Invites: "Invites",
  Referrals: "Referrals",
  Dashboard: "Dashboard",
  Privacy: "Privacy",
  Presigned: "Presigned",
  Media: "Media",
  SYSTEM_FEEDBACK: "System Feedback",
  Emails: "Emails",
  Marketplace: "Marketplace",
  GlobalMarketplace: "Global Marketplace",
  Recruitment: "Recruitment",
  Backfill: "Backfill",
} as const;
