export const EMAILS_MESSAGES = {
  INFO: {
    SENDING_EMAIL: (to: string) => `Sending email to ${to}`,
    SENDING_INTRODUCTION: (to: string, sender: string) =>
      `Sending introduction email to ${to} from ${sender}`,
    EMAIL_SENT_SUCCESS: (to: string, id?: string) =>
      `Email sent successfully to ${to}${id ? `. Email ID: ${id}` : ""}`,
    INTRODUCTION_SENT_SUCCESS: (id: string) =>
      `Introduction email sent successfully. Email ID: ${id}`,
    ACCESS_TOKEN_REFRESHED: "Access token refreshed successfully",
  },
  WARN: {
    RESEND_NOT_CONFIGURED:
      "RESEND_API_KEY not configured - email sending disabled",
    SKIPPING_SEND: "Resend not configured - skipping email send",
    RETRYING: (
      context: string,
      attempt: number,
      max: number,
      error: string,
      delay: number
    ) =>
      `${context} - Attempt ${attempt}/${max} failed with retryable error: ${error}. Retrying in ${delay}ms...`,
  },
  ERROR: {
    RESEND_API_ERROR: (error: string) => `Resend API error: ${error}`,
    SEND_FAILED: (to: string, error: string) =>
      `Failed to send email to ${to}: ${error}`,
    CONFIRMATION_SEND_FAILED:
      "Resend not configured - cannot send meeting confirmation email",
    INTRODUCTION_SEND_FAILED:
      "Resend not configured - cannot send introduction email",
    SERVICE_NOT_CONFIGURED:
      "Email service not configured - RESEND_API_KEY is missing",
    NO_EMAIL_ID: "Resend API did not return email ID",
    UPDATE_REQUEST_FAILED: (id: string, error: string) =>
      `❌ Error updating introduction request ${id}: ${error}`,
    TEMPLATE_NOT_FOUND: "Template not found or not active",
    EMAIL_CONTENT_MISSING:
      "Email content is missing. Provide html, text, or template.",
  },
  SUBJECTS: {
    INTRODUCTION_REQUEST: (name: string) =>
      `New Introduction Request from ${name}`,
    MEETING_SCHEDULED: "Meeting Scheduled",
    MEETING_CONFIRMED: (otherParty: string, date: string) =>
      `Meeting Confirmed: ${otherParty} - ${date}`,
  },
} as const;

export const EMAIL_RETRY_PATTERNS = [
  "unable to fetch",
  "request could not be resolved",
  "network",
  "timeout",
  "econnreset",
  "econnrefused",
  "enotfound",
  "socket hang up",
  "fetch failed",
];

export const EMAIL_CONFIG = {
  MAX_RETRIES: 3,
  RETRY_DELAY_MS: 1000,
  DEFAULT_FROM: "onboarding@resend.dev",
  DEFAULT_NOREPLY: "noreply@prospectly.com",
} as const;

export enum EmailTemplateStatus {
  DRAFT = "draft",
  ACTIVE = "active",
  ARCHIVED = "archived",
}

export enum EmailTemplateCategory {
  ONBOARDING = "onboarding",
  AUTHENTICATION = "authentication",
  NOTIFICATIONS = "notifications",
  BILLING = "billing",
  REPORTS = "reports",
  MARKETING = "marketing",
  SUPPORT = "support",
  INTRODUCTIONS = "introductions",
  MEETINGS = "meetings",
  SUBSCRIPTIONS = "subscriptions",
  RECRUITMENT = "recruitment",
}

export enum Slug {
  Authentication = "admin_authentication",
  Introduction = "admin_introduction",
  PasswordReset = "admin_password_reset",
  PasswordForgot = "admin_password_forgot",
  Welcome = "admin_welcome",
  AccountVerification = "admin_account_verification",
  IntroductionRequest = "introduction_request",
  MeetingScheduled = "meeting_scheduled",
  MeetingConfirmation = "meeting_confirmation",
  IntroductionEmail = "introduction_email",
  InviteEmail = "invite_email",
  SubscriptionPurchase = "subscription_purchase",
  SubscriptionUpgrade = "subscription_upgrade",
  SubscriptionDowngrade = "subscription_downgrade",
  SubscriptionCancellation = "subscription_cancellation",
  SubscriptionRenewal = "subscription_renewal",
  PayoutStart = "payout_start",
  PayoutComplete = "payout_complete",
  CandidateConsent = "candidate_consent",
  RecruitmentInterviewInvite = "recruitment_interview_invite",
  RecruitmentInterviewBookingError = "recruitment_interview_booking_error",
  RecruitmentRecruiterNewCandidate = "recruitment_recruiter_new_candidate",
  RecruitmentCandidateShortlisted = "recruitment_candidate_shortlisted",
  RecruitmentConnectorShortlisted = "recruitment_connector_shortlisted",
  RecruitmentConnectorInterviewInviteSent = "recruitment_connector_interview_invite_sent",
  RecruitmentConnectorInterviewScheduled = "recruitment_connector_interview_scheduled",
  RecruitmentConnectorInterviewCompleted = "recruitment_connector_interview_completed",
  RecruitmentCandidateHired = "recruitment_candidate_hired",
  RecruitmentConnectorHired = "recruitment_connector_hired",
  RecruitmentCandidateRejected = "recruitment_candidate_rejected",
  RecruitmentConnectorRejected = "recruitment_connector_rejected",
  RecruitmentCandidatePayoutSetup = "recruitment_candidate_payout_setup",
  RecruitmentConnectorPayoutSetup = "recruitment_connector_payout_setup",
  RecruitmentCandidatePayoutReleased = "recruitment_candidate_payout_released",
  RecruitmentConnectorPayoutReleased = "recruitment_connector_payout_released",
  RecruitmentNewJobPost = "recruitment_new_job_post",
  RecruitmentCollaboratorAdded = "recruitment_collaborator_added",
  RecruitmentCandidateInReviewStatus = "recruitment_candidate_in_review_status",
  RecruitmentConnectorInReviewStatus = "recruitment_connector_in_review_status",
  RecruitmentJobClosedConnector = "recruitment_job_closed_connector",
  RecruitmentJobClosedCandidate = "recruitment_job_closed_candidate",
  RecruitmentJobReopenedConnector = "recruitment_job_reopened_connector",
  RecruitmentJobReopenedCandidate = "recruitment_job_reopened_candidate",
  ContactImportReminder = "contact_import_reminder",
  IntroductionRequestAccepted = "introduction_request_accepted",
  IntroductionSentRequester = "introduction_sent_requester",
  IntroductionFeedbackRequest = "introduction_feedback_request",
  IntroductionMeetingAckRequester = "introduction_meeting_ack_requester",
  MarketplaceSharerRequestClaimed = "marketplace_sharer_request_claimed",
  IntroductionRequestUnsuccessful = "introduction_request_unsuccessful",
  SystemFeedbackSubmitted = "system_feedback_submitted",
  SystemFeedbackAcknowledgement = "system_feedback_acknowledgement",
  SystemFeedbackStatusChanged = "system_feedback_status_changed",
}

/** Variables injected automatically for every template render */
export const EMAIL_TEMPLATE_COMMON_VARIABLES = ["currentYear", "url"] as const;

/**
 * Template variables mapping for each email template slug
 * Used to provide available variables to the UI
 */
export const EMAIL_TEMPLATE_VARIABLES: Record<string, string[]> = {
  [Slug.Authentication]: ["url"],
  [Slug.Introduction]: ["url"],
  [Slug.PasswordReset]: ["url"],
  [Slug.PasswordForgot]: ["url"],
  [Slug.Welcome]: ["fullName", "url"],
  [Slug.AccountVerification]: ["url"],
  [Slug.IntroductionEmail]: [
    "targetName",
    "requesterName",
    "greetingName",
    "emailBody",
    "bookingLink",
    "connectorName",
    "requesterAvatar",
    "isTarget",
    "url",
  ],
  [Slug.InviteEmail]: ["senderName", "inviteLink", "inviteText", "url"],
  [Slug.MeetingConfirmation]: [
    "recipientName",
    "otherPartyName",
    "connectorName",
    "meetingDate",
    "meetingTime",
    "meetingTimezone",
    "meetingDuration",
    "meetingLink",
    "meetingPurpose",
    "roleDescription",
    "url",
  ],
  [Slug.IntroductionRequest]: [
    "requesterName",
    "prospectName",
    "prospectFirstName",
    "contactName",
    "bountyAmount",
    "message",
    "inboxUrl",
    "url",
  ],
  [Slug.IntroductionRequestAccepted]: [
    "requesterName",
    "connectorName",
    "prospectName",
    "acceptedDate",
    "pipelineUrl",
    "url",
  ],
  [Slug.IntroductionSentRequester]: [
    "requesterName",
    "connectorName",
    "prospectName",
    "sentDate",
    "pipelineUrl",
    "url",
  ],
  [Slug.IntroductionFeedbackRequest]: [
    "recipientName",
    "otherPartyName",
    "meetingTitle",
    "role",
    "feedbackUrl",
    "url",
  ],
  [Slug.IntroductionMeetingAckRequester]: [
    "requesterName",
    "requesterFirstName",
    "connectorName",
    "prospectName",
    "meetingTitle",
    "pipelineUrl",
    "url",
  ],
  [Slug.MeetingScheduled]: ["contactName", "meetingDate", "meetingTime", "url"],
  [Slug.SubscriptionPurchase]: [
    "userName",
    "planName",
    "amount",
    "interval",
    "url",
  ],
  [Slug.SubscriptionUpgrade]: [
    "userName",
    "oldPlanName",
    "newPlanName",
    "amount",
    "interval",
    "url",
  ],
  [Slug.SubscriptionDowngrade]: [
    "userName",
    "oldPlanName",
    "newPlanName",
    "amount",
    "interval",
    "url",
  ],
  [Slug.SubscriptionCancellation]: [
    "userName",
    "planName",
    "effectiveDate",
    "url",
  ],
  [Slug.SubscriptionRenewal]: [
    "userName",
    "planName",
    "amount",
    "interval",
    "nextBillingDate",
    "url",
  ],
  [Slug.PayoutStart]: ["requesterName", "url"],
  [Slug.PayoutComplete]: ["amount", "requesterName", "url"],
  [Slug.CandidateConsent]: [
    "candidateName",
    "connectorName",
    "jobTitle",
    "companyName",
    "consentLink",
    "url",
  ],
  [Slug.RecruitmentInterviewInvite]: [
    "candidateName",
    "jobTitle",
    "companyName",
    "recruiterName",
    "recruiterTitle",
    "interviewNotes",
    "bookingLink",
    "url",
  ],
  [Slug.RecruitmentInterviewBookingError]: [
    "recruiterName",
    "candidateName",
    "jobTitle",
    "companyName",
    "errorMessage",
    "errorStage",
    "pipelineUrl",
    "url",
  ],
  [Slug.RecruitmentRecruiterNewCandidate]: [
    "recruiterName",
    "jobTitle",
    "companyName",
    "matchScore",
    "pipelineUrl",
    "url",
  ],
  [Slug.RecruitmentCandidateShortlisted]: [
    "candidateName",
    "jobTitle",
    "companyName",
    "applicationsUrl",
    "url",
  ],
  [Slug.RecruitmentConnectorShortlisted]: [
    "connectorName",
    "candidateName",
    "jobTitle",
    "companyName",
    "payoutAmount",
    "pipelineUrl",
    "stripeSetupUrl",
    "url",
  ],
  [Slug.RecruitmentConnectorInterviewInviteSent]: [
    "connectorName",
    "candidateName",
    "jobTitle",
    "companyName",
    "payoutAmount",
    "pipelineUrl",
    "stripeSetupUrl",
    "url",
  ],
  [Slug.RecruitmentConnectorInterviewScheduled]: [
    "connectorName",
    "candidateName",
    "jobTitle",
    "companyName",
    "payoutAmount",
    "pipelineUrl",
    "stripeSetupUrl",
    "url",
  ],
  [Slug.RecruitmentConnectorInterviewCompleted]: [
    "connectorName",
    "candidateName",
    "jobTitle",
    "companyName",
    "payoutAmount",
    "pipelineUrl",
    "stripeSetupUrl",
    "url",
  ],
  [Slug.RecruitmentCandidateHired]: [
    "candidateName",
    "jobTitle",
    "companyName",
    "hireDate",
    "hasSuccessFee",
    "successFeeAmount",
    "successBonusEligibilityText",
    "applicationsUrl",
    "stripeSetupUrl",
    "url",
  ],
  [Slug.RecruitmentConnectorHired]: [
    "connectorName",
    "candidateName",
    "jobTitle",
    "companyName",
    "hireDate",
    "payoutAmount",
    "connectorPayoutWaitDays",
    "connectorWaitEndsAt",
    "pipelineUrl",
    "stripeSetupUrl",
    "url",
  ],
  [Slug.RecruitmentCandidateRejected]: [
    "candidateName",
    "jobTitle",
    "companyName",
    "rejectionCategory",
    "rejectionNote",
    "jobMarketplaceUrl",
    "applicationsUrl",
    "url",
  ],
  [Slug.RecruitmentConnectorRejected]: [
    "recipientName",
    "candidateName",
    "jobTitle",
    "companyName",
    "rejectionCategory",
    "rejectionNote",
    "actionUrl",
    "jobMarketplaceUrl",
    "url",
  ],
  [Slug.RecruitmentCandidatePayoutSetup]: [
    "recipientName",
    "jobTitle",
    "companyName",
    "payoutAmount",
    "stripeSetupUrl",
    "url",
  ],
  [Slug.RecruitmentConnectorPayoutSetup]: [
    "recipientName",
    "jobTitle",
    "companyName",
    "payoutAmount",
    "stripeSetupUrl",
    "url",
  ],
  [Slug.RecruitmentCandidatePayoutReleased]: [
    "recipientName",
    "jobTitle",
    "companyName",
    "payoutAmount",
    "basePayoutAmount",
    "creditsUsedAmount",
    "creditsRemainingAfter",
    "hasCreditsApplied",
    "hasCreditsRemainingAfter",
    "releasedDate",
    "estimatedCreditDate",
    "needsBankSetup",
    "stripeSetupUrl",
    "url",
  ],
  [Slug.RecruitmentConnectorPayoutReleased]: [
    "recipientName",
    "candidateName",
    "jobTitle",
    "companyName",
    "payoutAmount",
    "basePayoutAmount",
    "creditsUsedAmount",
    "creditsRemainingAfter",
    "hasCreditsApplied",
    "hasCreditsRemainingAfter",
    "releasedDate",
    "estimatedCreditDate",
    "needsBankSetup",
    "stripeSetupUrl",
    "url",
  ],
  [Slug.RecruitmentNewJobPost]: [
    "jobTitle",
    "companyName",
    "location",
    "workType",
    "salaryRange",
    "connectorPayout",
    "successBonus",
    "jobUrl",
    "url",
  ],
  [Slug.RecruitmentCollaboratorAdded]: [
    "collaboratorName",
    "ownerName",
    "jobTitle",
    "companyName",
    "jobUrl",
    "url",
  ],
  [Slug.RecruitmentCandidateInReviewStatus]: [
    "candidateName",
    "jobTitle",
    "companyName",
    "applicationsUrl",
    "url",
  ],
  [Slug.RecruitmentConnectorInReviewStatus]: [
    "connectorName",
    "candidateName",
    "jobTitle",
    "companyName",
    "pipelineUrl",
    "url",
  ],
  [Slug.RecruitmentJobClosedConnector]: [
    "recipientName",
    "jobTitle",
    "companyName",
    "jobMarketplaceUrl",
    "connectorPipelineUrl",
    "url",
  ],
  [Slug.RecruitmentJobClosedCandidate]: [
    "candidateName",
    "jobTitle",
    "companyName",
    "applicationsUrl",
    "jobMarketplaceUrl",
    "emailPreferencesUrl",
    "url",
  ],
  [Slug.RecruitmentJobReopenedConnector]: [
    "recipientName",
    "jobTitle",
    "companyName",
    "jobMarketplaceUrl",
    "connectorPipelineUrl",
    "url",
  ],
  [Slug.RecruitmentJobReopenedCandidate]: [
    "candidateName",
    "jobTitle",
    "companyName",
    "applicationsUrl",
    "jobMarketplaceUrl",
    "emailPreferencesUrl",
    "url",
  ],
  [Slug.ContactImportReminder]: ["firstName", "userName", "url"],
  [Slug.IntroductionRequestUnsuccessful]: [
    "requesterName",
    "meetingTitle",
    "prospectName",
    "connectorName",
    "failureReason",
    "failureNotes",
    "unsuccessfulDate",
    "emailHeadline",
    "nextStepBody",
    "ctaUrl",
    "ctaLabel",
    "url",
  ],
  [Slug.MarketplaceSharerRequestClaimed]: [
    "sharerName",
    "claimerName",
    "prospectName",
    "requesterName",
    "bountyAmount",
    "sharerShare",
    "claimedDate",
    "claimsUrl",
    "splitPercentage",
    "url",
  ],
  [Slug.SystemFeedbackSubmitted]: [
    "submitterLabel",
    "userEmail",
    "feedbackType",
    "feedbackPriority",
    "feedbackTitle",
    "feedbackDescription",
    "submittedAt",
    "attachmentCount",
    "adminFeedbackUrl",
    "userPanelUrl",
    "url",
  ],
  [Slug.SystemFeedbackAcknowledgement]: ["userName", "userPanelUrl", "url"],
  [Slug.SystemFeedbackStatusChanged]: [
    "userName",
    "feedbackTitle",
    "previousStatus",
    "newStatus",
    "statusLabel",
    "updatedAt",
    "userPanelUrl",
    "url",
  ],
} as const;
