export type PfFinanceTab =
  | "overview"
  | "transactions"
  | "payouts"
  | "payments"
  | "disputes";

export const PF_RECENT_TRANSACTIONS = [
  {
    contact: "Sarah Chen",
    desc: "Connector payout — NovaTech intro",
    amount: 375,
    positive: true,
    date: "12 Jun 2026",
    status: "Completed",
    tone: "gn",
  },
  {
    contact: "David Kim",
    desc: "Bounty hold — Pinnacle SaaS demo",
    amount: 850,
    positive: false,
    date: "11 Jun 2026",
    status: "In Progress",
    tone: "am",
  },
  {
    contact: "David Kim",
    desc: "Sharer commission — marketplace share",
    amount: 250,
    positive: true,
    date: "9 Jun 2026",
    status: "Completed",
    tone: "gn",
  },
  {
    contact: "Rachel Moore",
    desc: "Bounty hold — Ops automation discovery",
    amount: 400,
    positive: false,
    date: "7 Jun 2026",
    status: "In Progress",
    tone: "am",
  },
  {
    contact: "Chris Nguyen",
    desc: "Partial refund — unfulfilled intro",
    amount: 150,
    positive: true,
    date: "5 Jun 2026",
    status: "Completed",
    tone: "gn",
  },
] as const;

export const PF_PAYOUT_TIMELINE = [
  {
    contact: "David Kim",
    meeting: "Pinnacle SaaS product demo",
    amount: 338,
    status: "Pending",
    tone: "am",
    date: "Expected 18 Jun",
  },
  {
    contact: "Sarah Chen",
    meeting: "NovaTech partnership intro",
    amount: 225,
    status: "Pending",
    tone: "am",
    date: "Expected 20 Jun",
  },
  {
    contact: "David Kim",
    meeting: "Marketplace share commission",
    amount: 225,
    status: "Completed",
    tone: "gn",
    date: "10 Jun 2026",
  },
  {
    contact: "Elena Voss",
    meeting: "Healthcare data partnership",
    amount: 765,
    status: "Completed",
    tone: "gn",
    date: "28 May 2026",
  },
] as const;

export const PF_TRANSACTION_ROWS = [
  {
    contact: "Sarah Chen",
    via: "Marcus Reed",
    meeting: "Explore NovaTech partnership fit",
    stage: "Active",
    stageTone: "bl",
    amount: 750,
    payment: "In Progress",
    payTone: "am",
    date: "14 Jun 2026, 11:08 PM",
  },
  {
    contact: "David Kim",
    via: "Marcus Reed",
    meeting: "Pinnacle SaaS product demo",
    stage: "Completed",
    stageTone: "gn",
    amount: 500,
    payment: "Completed",
    payTone: "gn",
    date: "1 Jun 2026, 4:22 PM",
  },
  {
    contact: "David Kim",
    via: null,
    meeting: "Marketplace share commission",
    stage: "Completed",
    stageTone: "gn",
    amount: 250,
    payment: "Completed",
    payTone: "gn",
    date: "23 May 2026, 9:15 AM",
  },
  {
    contact: "Rachel Moore",
    via: "Jordan Lee",
    meeting: "Insurance VA workflow review",
    stage: "Active",
    stageTone: "bl",
    amount: 400,
    payment: "In Progress",
    payTone: "am",
    date: "13 Jun 2026, 3:40 PM",
  },
  {
    contact: "Elena Voss",
    via: "Marcus Reed",
    meeting: "Healthcare data partnership",
    stage: "Completed",
    stageTone: "gn",
    amount: 850,
    payment: "Completed",
    payTone: "gn",
    date: "28 May 2026, 2:15 PM",
  },
  {
    contact: "James Okafor",
    via: "Taylor Brooks",
    meeting: "Investor network intro",
    stage: "Completed",
    stageTone: "gn",
    amount: 950,
    payment: "Completed",
    payTone: "gn",
    date: "20 May 2026, 10:30 AM",
  },
  {
    contact: "Chris Nguyen",
    via: null,
    meeting: "Partial refund — unfulfilled intro",
    stage: "Completed",
    stageTone: "gn",
    amount: 150,
    payment: "Refunded",
    payTone: "pu",
    date: "5 Jun 2026, 8:00 AM",
  },
  {
    contact: "Alex Rivera",
    via: "Marcus Reed",
    meeting: "Explore NovaTech partnership fit",
    stage: "Active",
    stageTone: "bl",
    amount: 750,
    payment: "Authorized",
    payTone: "bl",
    date: "15 Jun 2026, 6:20 PM",
  },
] as const;

export const PF_PAYOUT_ROWS = [
  {
    contact: "David Kim",
    meeting: "Pinnacle SaaS product demo",
    gross: 375,
    net: 338,
    status: "Pending",
    statusTone: "am",
    date: "Pending",
  },
  {
    contact: "Sarah Chen",
    meeting: "NovaTech partnership intro",
    gross: 250,
    net: 225,
    status: "Pending",
    statusTone: "am",
    date: "Pending",
  },
  {
    contact: "David Kim",
    meeting: "Marketplace share commission",
    gross: 250,
    net: 225,
    status: "Completed",
    statusTone: "gn",
    date: "10 Jun 2026",
  },
  {
    contact: "Elena Voss",
    meeting: "Healthcare data partnership",
    gross: 850,
    net: 765,
    status: "Completed",
    statusTone: "gn",
    date: "28 May 2026",
  },
  {
    contact: "James Okafor",
    meeting: "Investor network intro",
    gross: 950,
    net: 855,
    status: "Processing",
    statusTone: "bl",
    date: "22 May 2026",
  },
  {
    contact: "Rachel Moore",
    meeting: "Ops automation discovery",
    gross: 400,
    net: 360,
    status: "Pending",
    statusTone: "am",
    date: "Pending",
  },
] as const;

export const PF_CHART_BARS = [
  { label: "Jun 1", earn: 180, spend: 60 },
  { label: "Jun 3", earn: 220, spend: 80 },
  { label: "Jun 5", earn: 140, spend: 45 },
  { label: "Jun 7", earn: 310, spend: 120 },
  { label: "Jun 9", earn: 260, spend: 90 },
  { label: "Jun 11", earn: 390, spend: 140 },
  { label: "Jun 13", earn: 420, spend: 155 },
];
