export function HeroRightBgSvg() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 560 560"
      fill="none"
      className="h-full w-full"
      aria-hidden
    >
      <circle
        cx="280"
        cy="280"
        r="100"
        stroke="hsl(var(--home-amethyst))"
        strokeWidth=".6"
        opacity=".1"
        strokeDasharray="4 6"
      />
      <circle
        cx="280"
        cy="280"
        r="170"
        stroke="hsl(var(--home-rose))"
        strokeWidth=".5"
        opacity=".08"
        strokeDasharray="3 8"
      />
      <circle
        cx="280"
        cy="280"
        r="240"
        stroke="hsl(var(--home-sky))"
        strokeWidth=".4"
        opacity=".06"
        strokeDasharray="2 10"
      />
      <line
        x1="280"
        y1="280"
        x2="120"
        y2="100"
        stroke="hsl(var(--home-amethyst))"
        strokeWidth=".6"
        opacity=".1"
      />
      <line
        x1="280"
        y1="280"
        x2="460"
        y2="120"
        stroke="hsl(var(--home-rose))"
        strokeWidth=".6"
        opacity=".08"
      />
      <line
        x1="280"
        y1="280"
        x2="80"
        y2="320"
        stroke="hsl(var(--home-sky))"
        strokeWidth=".5"
        opacity=".07"
      />
      <line
        x1="280"
        y1="280"
        x2="480"
        y2="380"
        stroke="hsl(var(--home-amethyst))"
        strokeWidth=".5"
        opacity=".08"
      />
      <line
        x1="280"
        y1="280"
        x2="180"
        y2="480"
        stroke="hsl(var(--home-rose))"
        strokeWidth=".5"
        opacity=".06"
      />
      <line
        x1="280"
        y1="280"
        x2="420"
        y2="500"
        stroke="hsl(var(--home-sky))"
        strokeWidth=".4"
        opacity=".06"
      />
      <line
        x1="280"
        y1="280"
        x2="50"
        y2="180"
        stroke="hsl(var(--home-amethyst))"
        strokeWidth=".4"
        opacity=".05"
      />
      <line
        x1="280"
        y1="280"
        x2="520"
        y2="220"
        stroke="hsl(var(--home-rose))"
        strokeWidth=".4"
        opacity=".05"
      />
      <circle cx="120" cy="100" r="5" fill="hsl(var(--home-amethyst))">
        <animate
          attributeName="opacity"
          values=".1;.35;.1"
          dur="3s"
          repeatCount="indefinite"
        />
      </circle>
      <circle cx="460" cy="120" r="4.5" fill="hsl(var(--home-rose))">
        <animate
          attributeName="opacity"
          values=".08;.3;.08"
          dur="3.5s"
          repeatCount="indefinite"
          begin=".5s"
        />
      </circle>
      <circle cx="80" cy="320" r="4" fill="hsl(var(--home-sky))">
        <animate
          attributeName="opacity"
          values=".08;.28;.08"
          dur="4s"
          repeatCount="indefinite"
          begin="1s"
        />
      </circle>
      <circle cx="480" cy="380" r="5" fill="hsl(var(--home-amethyst))">
        <animate
          attributeName="opacity"
          values=".1;.32;.1"
          dur="3s"
          repeatCount="indefinite"
          begin="1.5s"
        />
      </circle>
      <circle cx="180" cy="480" r="4" fill="hsl(var(--home-rose))">
        <animate
          attributeName="opacity"
          values=".06;.25;.06"
          dur="4.5s"
          repeatCount="indefinite"
          begin="2s"
        />
      </circle>
      <circle cx="420" cy="500" r="4.5" fill="hsl(var(--home-sky))">
        <animate
          attributeName="opacity"
          values=".08;.28;.08"
          dur="3.5s"
          repeatCount="indefinite"
          begin=".8s"
        />
      </circle>
      <circle cx="50" cy="180" r="3" fill="hsl(var(--home-amethyst))">
        <animate
          attributeName="opacity"
          values=".05;.2;.05"
          dur="4s"
          repeatCount="indefinite"
          begin="1.2s"
        />
      </circle>
      <circle cx="520" cy="220" r="3.5" fill="hsl(var(--home-rose))">
        <animate
          attributeName="opacity"
          values=".06;.22;.06"
          dur="3s"
          repeatCount="indefinite"
          begin="1.8s"
        />
      </circle>
      <circle r="2" fill="hsl(var(--home-amethyst))" opacity=".4">
        <animate
          attributeName="cx"
          values="280;120"
          dur="4s"
          repeatCount="indefinite"
        />
        <animate
          attributeName="cy"
          values="280;100"
          dur="4s"
          repeatCount="indefinite"
        />
        <animate
          attributeName="opacity"
          values="0;.4;0"
          dur="4s"
          repeatCount="indefinite"
        />
      </circle>
      <circle r="2" fill="hsl(var(--home-rose))" opacity=".35">
        <animate
          attributeName="cx"
          values="280;460"
          dur="5s"
          repeatCount="indefinite"
          begin="1s"
        />
        <animate
          attributeName="cy"
          values="280;120"
          dur="5s"
          repeatCount="indefinite"
          begin="1s"
        />
        <animate
          attributeName="opacity"
          values="0;.35;0"
          dur="5s"
          repeatCount="indefinite"
          begin="1s"
        />
      </circle>
      <circle r="2" fill="hsl(var(--home-sky))" opacity=".3">
        <animate
          attributeName="cx"
          values="280;480"
          dur="4.5s"
          repeatCount="indefinite"
          begin="2s"
        />
        <animate
          attributeName="cy"
          values="280;380"
          dur="4.5s"
          repeatCount="indefinite"
          begin="2s"
        />
        <animate
          attributeName="opacity"
          values="0;.3;0"
          dur="4.5s"
          repeatCount="indefinite"
          begin="2s"
        />
      </circle>
      <circle cx="160" cy="200" r="1.5" fill="hsl(var(--home-amethyst))">
        <animate
          attributeName="opacity"
          values=".05;.15;.05"
          dur="3s"
          repeatCount="indefinite"
        />
      </circle>
      <circle cx="400" cy="250" r="1.5" fill="hsl(var(--home-rose))">
        <animate
          attributeName="opacity"
          values=".04;.14;.04"
          dur="3.5s"
          repeatCount="indefinite"
          begin=".5s"
        />
      </circle>
      <circle cx="350" cy="450" r="1.5" fill="hsl(var(--home-sky))">
        <animate
          attributeName="opacity"
          values=".04;.12;.04"
          dur="4s"
          repeatCount="indefinite"
          begin="1s"
        />
      </circle>
      <circle cx="200" cy="380" r="1.5" fill="hsl(var(--home-amethyst))">
        <animate
          attributeName="opacity"
          values=".03;.12;.03"
          dur="3s"
          repeatCount="indefinite"
          begin="1.5s"
        />
      </circle>
    </svg>
  );
}
