import type { KanbanCandidate, JobDetail } from "./types";

export const mockJob: JobDetail = {
  id: "job-1",
  title: "Senior Software Engineer",
  companyName: "Acme Corporation",
  location: "San Francisco, CA",
  workType: "hybrid",
  status: "active",
  salaryRange: { min: 150000, max: 200000, currency: "USD" },
  bountyAmount: 17500,
  interviewsUsed: 1,
  createdAt: "2026-01-15",
  skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS", "Docker"],
};

export const mockCandidates: KanbanCandidate[] = [
  {
    id: "c1",
    anonymousId: "Candidate #A7",
    avatarColor: "bg-teal-100 text-teal-700",
    matchScore: 92,
    matchBreakdown: { skills: 95, experience: 90, salary: 88 },
    currentTitle: "Senior Software Engineer",
    currentCompany: "Top Tech Company",
    experienceYears: 7,
    skills: ["React", "TypeScript", "Node.js", "AWS", "PostgreSQL", "GraphQL"],
    expectedSalary: 175000,
    noticePeriodDays: 30,
    availability: "2 weeks",
    stage: "interview_scheduled",
    stageUpdatedAt: "2026-01-20",
    connectorAnonymousId: "Connector #M4",
    referralType: "direct",
    revealedName: "Alex Johnson",
    revealedEmail: "alex.j@email.com",
    revealedLinkedIn: "https://linkedin.com/in/alexj",
  },
  {
    id: "c2",
    anonymousId: "Candidate #B3",
    avatarColor: "bg-cyan-100 text-cyan-700",
    matchScore: 87,
    matchBreakdown: { skills: 88, experience: 85, salary: 90 },
    currentTitle: "Full Stack Developer",
    currentCompany: "Series B Startup",
    experienceYears: 5,
    skills: ["React", "Node.js", "TypeScript", "MongoDB", "Docker"],
    expectedSalary: 160000,
    noticePeriodDays: 14,
    availability: "Immediate",
    stage: "shortlisted",
    stageUpdatedAt: "2026-01-19",
    connectorAnonymousId: "Connector #K2",
    referralType: "direct",
  },
  {
    id: "c3",
    anonymousId: "Candidate #C1",
    avatarColor: "bg-blue-100 text-blue-700",
    matchScore: 78,
    matchBreakdown: { skills: 80, experience: 75, salary: 82 },
    currentTitle: "Software Engineer",
    currentCompany: "Enterprise Corp",
    experienceYears: 4,
    skills: ["React", "JavaScript", "Python", "AWS"],
    expectedSalary: 155000,
    noticePeriodDays: 30,
    availability: "1 month",
    stage: "in_review",
    stageUpdatedAt: "2026-01-21",
    connectorAnonymousId: "Connector #P1",
    referralType: "public_claim",
  },
  {
    id: "c4",
    anonymousId: "Candidate #D5",
    avatarColor: "bg-purple-100 text-purple-700",
    matchScore: 95,
    matchBreakdown: { skills: 98, experience: 92, salary: 95 },
    currentTitle: "Staff Engineer",
    currentCompany: "FAANG Company",
    experienceYears: 9,
    skills: [
      "React",
      "TypeScript",
      "Node.js",
      "System Design",
      "Kubernetes",
      "AWS",
    ],
    expectedSalary: 195000,
    noticePeriodDays: 60,
    availability: "2 months",
    stage: "shortlisted",
    stageUpdatedAt: "2026-01-18",
    connectorAnonymousId: "Connector #M4",
    referralType: "direct",
  },
  {
    id: "c5",
    anonymousId: "Candidate #E2",
    avatarColor: "bg-pink-100 text-pink-700",
    matchScore: 65,
    matchBreakdown: { skills: 60, experience: 70, salary: 65 },
    currentTitle: "Junior Developer",
    currentCompany: "Small Agency",
    experienceYears: 2,
    skills: ["React", "JavaScript", "CSS"],
    expectedSalary: 120000,
    noticePeriodDays: 14,
    stage: "rejected",
    stageUpdatedAt: "2026-01-17",
    connectorAnonymousId: "Connector #J3",
    rejectionReason: "Insufficient experience for senior role",
  },
  {
    id: "c6",
    anonymousId: "Candidate #F8",
    avatarColor: "bg-orange-100 text-orange-700",
    matchScore: 82,
    matchBreakdown: { skills: 85, experience: 80, salary: 78 },
    currentTitle: "Backend Engineer",
    currentCompany: "FinTech Startup",
    experienceYears: 6,
    skills: ["Node.js", "TypeScript", "PostgreSQL", "Redis", "Docker"],
    expectedSalary: 170000,
    noticePeriodDays: 30,
    stage: "in_review",
    stageUpdatedAt: "2026-01-20",
    connectorAnonymousId: "Connector #K2",
    referralType: "direct",
  },
  {
    id: "c7",
    anonymousId: "Candidate #G4",
    avatarColor: "bg-indigo-100 text-indigo-700",
    matchScore: 88,
    matchBreakdown: { skills: 90, experience: 85, salary: 88 },
    currentTitle: "Senior Frontend Engineer",
    currentCompany: "E-commerce Giant",
    experienceYears: 6,
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Testing"],
    expectedSalary: 165000,
    noticePeriodDays: 21,
    stage: "in_review",
    stageUpdatedAt: "2026-01-21",
    connectorAnonymousId: "Connector #P1",
    referralType: "direct",
  },
];
