import type { SharedDeal } from "./types";

export const mockSharedDeals: SharedDeal[] = [
  {
    id: "shared-1",
    dealId: "deal-1",
    sharerCode: "abc123xyz",
    prospect: {
      name: "Jane Smith",
      title: "VP of Marketing",
      company: "Acme Corp",
    },
    meetingTitle: "Partnership discussion for marketing automation",
    bountyAmount: 500,
    connectorEarnings: 250,
    status: "active",
    sharedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    analytics: {
      totalShares: 5,
      sharesByPlatform: { facebook: 1, twitter: 2, linkedin: 1, copy: 1 },
      totalClicks: 23,
      signupAttempts: 3,
      claimAttempts: 2,
      successfulClaims: 0,
    },
    claimers: [
      {
        name: "Amelia Stone",
        platform: "linkedin",
        status: "in_progress",
        progress: 45,
      },
      {
        name: "Jason Lee",
        platform: "twitter",
        status: "failed",
        progress: 20,
        reason: "Prospect not found in contacts",
      },
    ],
  },
  {
    id: "shared-2",
    dealId: "deal-2",
    sharerCode: "def456uvw",
    prospect: {
      name: "Michael Rodriguez",
      title: "CTO",
      company: "CloudTech Solutions",
    },
    meetingTitle: "AI infrastructure solutions demo",
    bountyAmount: 950,
    connectorEarnings: 475,
    status: "claimed",
    sharedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    analytics: {
      totalShares: 8,
      sharesByPlatform: { facebook: 2, twitter: 3, linkedin: 2, copy: 1 },
      totalClicks: 45,
      signupAttempts: 7,
      claimAttempts: 4,
      successfulClaims: 1,
    },
    claimedBy: { name: "Sarah Johnson", status: "pending_verification" },
    claimers: [
      {
        name: "Sarah Johnson",
        platform: "linkedin",
        status: "verified",
        progress: 70,
      },
      {
        name: "Derek Wu",
        platform: "facebook",
        status: "in_progress",
        progress: 35,
      },
      {
        name: "Priya Das",
        platform: "copy",
        status: "failed",
        progress: 20,
        reason: "Connector not in network",
      },
    ],
  },
  {
    id: "shared-3",
    dealId: "deal-3",
    sharerCode: "ghi789rst",
    prospect: {
      name: "David Chen",
      title: "Head of Product",
      company: "DataStream Corp",
    },
    meetingTitle: "Data analytics integration partnership",
    bountyAmount: 600,
    connectorEarnings: 300,
    status: "completed",
    sharedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    analytics: {
      totalShares: 12,
      sharesByPlatform: { facebook: 3, twitter: 4, linkedin: 3, copy: 2 },
      totalClicks: 78,
      signupAttempts: 12,
      claimAttempts: 6,
      successfulClaims: 1,
    },
    claimedBy: { name: "Alex Turner", status: "completed" },
    claimers: [
      {
        name: "Alex Turner",
        platform: "linkedin",
        status: "completed",
        progress: 100,
      },
      {
        name: "Jamie Park",
        platform: "twitter",
        status: "failed",
        progress: 40,
        reason: "Contacts import incomplete",
      },
    ],
  },
];
