apiVersion: v1
kind: ConfigMap
metadata:
  name: prospectly-backend-config
  namespace: default
data:
  NODE_ENV: "production"
  PORT: "5000"
  FRONTEND_URL: "https://learning-front.officebrain.com"
  API_URL: "https://learning-back.officebrain.com"
  CORS_ORIGINS: "https://learning-front.officebrain.com"
  COOKIE_DOMAIN: ".officebrain.com"
  AWS_SIGNED_URL_EXPIRATION: "3600"
