apiVersion: v1
kind: Secret
metadata:
  name: prospectly-backend-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql://username:password@db-host:5432/dbname" # TODO: Update this
